id: I858B794A
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-a5d9
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 14:39:02.945456+00:00
last_modified: 2023-09-28 14:39:02.945462+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM4030
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM4030
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཚན་ཉིད་བཞིའི་རྣམ་བཞག་བློ་གསལ་དགའ་སྟོན་སོགས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9534160575957052
  ocr_word_median_confidence_index: 0.99478675
bases:
  I1NLM4030_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM4030_001
      total_pages: 378
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM4030_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99478675
      ocr_word_mean_confidence_index: 0.9534160575957052
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
